# Generated by Django 6.0.3 on 2026-03-22 19:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=100, primary_key=True, serialize=False)),
                ('usuario_id', models.IntegerField()),
                ('lugar_nombre', models.CharField(max_length=200)),
                ('fecha_agregado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'favoritos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Resena',
            fields=[
                ('id', models.CharField(db_column='_id', editable=False, max_length=24, primary_key=True, serialize=False)),
                ('usuario_id', models.IntegerField()),
                ('usuario_nombre', models.CharField(max_length=100)),
                ('lugar_nombre', models.CharField(max_length=200)),
                ('puntuacion', models.IntegerField()),
                ('comentario', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'resenas',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='usuario',
            name='ban_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usuario',
            name='banned_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
