from django.urls import path
from . import views

# Define las URL para la aplicación
urlpatterns = [
    path('', views.inicio, name='inicio'),
    path('login/', views.login_usuario, name='login'),
    path('register/', views.registrar_usuario, name='register'),
    path('logout/', views.logout_usuario, name='logout'),
    path('home/', views.home_view, name='home'),
    path('regiones/', views.gestionar_regiones, name='gestionar_regiones'),
    path('regiones/eliminar/<str:region_nombre>/', views.eliminar_region, name='eliminar_region'),
    path('regiones/editar/<str:region_nombre>/', views.editar_region, name='editar_region'),
    path('lugares/', views.gestionar_lugares, name='gestionar_lugares'),
    path('lugares/eliminar/<str:lugar_nombre>/', views.eliminar_lugar, name='eliminar_lugar'),
    path('lugares/editar/<str:lugar_nombre>/', views.editar_lugar, name='editar_lugar'),
    path('sincronizar/', views.sincronizar_datos, name='sincronizar_datos'),
    path('lugares/borrar-todo/', views.borrar_todo_lugares, name='borrar_todo_lugares'),
    path('regiones/borrar-todo/', views.borrar_todo_regiones, name='borrar_todo_regiones'),
    path('explorar/', views.explorar_destinos, name='explorar_destinos'),
    path('destino/<str:nombre_lugar>/', views.detalle_lugar, name='detalle_lugar'),
    path('guardar-resena/<str:nombre_lugar>/', views.guardar_resena, name='guardar_resena'),
    path('borrar-resena/<str:nombre_lugar>/', views.borrar_resena, name='borrar_resena'),
    path('toggle-favorito/<str:nombre_lugar>/', views.toggle_favorito, name='toggle_favorito'),
    path('mis-rutas/', views.mis_itinerarios, name='mis_itinerarios'),
    path('crear-ruta/', views.crear_itinerario, name='crear_itinerario'),
    path('agregar-parada/<str:nombre_lugar>/', views.agregar_parada, name='agregar_parada'),
    path('rutas/<str:itinerario_id>/', views.detalle_itinerario, name='detalle_itinerario'),
    path('rutas/<str:itinerario_id>/quitar/<str:nombre_lugar>/', views.eliminar_parada, name='eliminar_parada'),
    path('rutas/eliminar/<str:itinerario_id>/', views.eliminar_itinerario, name='eliminar_itinerario'),
    path('rutas/<str:itinerario_id>/mover/<str:nombre_lugar>/<str:direccion>/', views.mover_parada, name='mover_parada'),
    path('estadisticas/', views.estadisticas_globales, name='estadisticas'),
    path('panel-admin/', views.panel_administracion, name='panel_admin'),
    path('panel-admin/usuario/<int:user_id>/banear/', views.banear_usuario, name='banear_usuario'),
    path('panel-admin/usuario/<int:user_id>/eliminar/', views.eliminar_usuario, name='eliminar_usuario'),
    path('panel-admin/resena/<str:resena_id>/eliminar/', views.eliminar_resena_admin, name='eliminar_resena_admin'),
    path('panel-admin/usuario/<int:user_id>/desbanear/', views.desbanear_usuario, name='desbanear_usuario'),
    path('itinerario/editar/<str:itinerario_id>/', views.editar_itinerario, name='editar_itinerario'),
]